sudo: required
dist: trusty
language: python
env:
  matrix:
    - RELEASE=trusty ARCH=i386
    - RELEASE=trusty ARCH=amd64
    - RELEASE=xenial ARCH=i386
    - RELEASE=xenial ARCH=amd64
    - RELEASE=yakkety ARCH=i386
    - RELEASE=yakkety ARCH=amd64
    - RELEASE=zesty ARCH=i386
    - RELEASE=zesty ARCH=amd64
before_install:
    - sudo apt-get update
    - sudo apt-get install -y make qemu-system-x86 genisoimage
    - sudo apt-get install -y -t trusty-backports autopkgtest
script: travis_wait 45 make version_codename_list=$RELEASE arch_list=$ARCH
