sudo: required
dist: trusty
language: python
env:
  matrix:
    - RELEASE=trusty
    - RELEASE=xenial
    - RELEASE=yakkety
    - RELEASE=zesty
before_install:
    - sudo apt-get update
    - sudo apt-get install -y make qemu-system-x86 genisoimage
    - sudo apt-get install -y -t trusty-backports autopkgtest
script: travis_wait 45 make version_codename_list=$RELEASE
